URL_ARANGO_DB = "http://localhost:8529"
DB_NAME = "words_database"

UNI_WORD_NODE = "words"
UNI_CHAR_NODE = "chars"
BI_WORD_NODE = "bigrams"
BI_CHAR_NODE = "bichars"
TRI_WORD_NODE = "trigrams"
TRI_CHAR_NODE = "trichars"

UNI_WORD_EDGE = "follows"
UNI_CHAR_EDGE = "charfollows"
BI_WORD_EDGE = "bifollows"
BI_CHAR_EDGE = "bicharfollows"
TRI_WORD_EDGE = "trifollows"
TRI_CHAR_EDGE = "tricharfollows"

UNI_WORDS_GRAPH = "relatedWords"
UNI_CHARS_GRAPH = "relatedChars"
BI_WORDS_GRAPH = "relatedBiWords"
BI_CHARS_GRAPH = "relatedBiChars"
TRI_WORDS_GRAPH = "relatedTriWords"
TRI_CHARS_GRAPH = "relatedTriChars"

EDGE_SEPARATOR = ";¬"
NODE_SEPARATOR = ":¬"
WORD_START_SYMBOL = "<>"
WORD_FINAL_SYMBOL = "</>"
TOTAL_COLLECTIONS = 18

GRAPH_TO_COLLECTION = {UNI_WORDS_GRAPH: UNI_WORD_NODE, BI_WORDS_GRAPH: BI_WORD_NODE, TRI_WORDS_GRAPH: TRI_WORD_NODE, UNI_CHARS_GRAPH: UNI_CHAR_NODE, BI_CHARS_GRAPH: BI_CHAR_NODE, TRI_CHARS_GRAPH: TRI_CHAR_NODE}
GRAPH_TO_OPTION = {UNI_WORDS_GRAPH: 1, BI_WORDS_GRAPH: 2, TRI_WORDS_GRAPH: 3, UNI_CHARS_GRAPH: 4, BI_CHARS_GRAPH: 5, TRI_CHARS_GRAPH: 6}